name: souqcom
description: "an Ecommerce app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #icons
  iconsax: ^0.0.8

  #state_management:
  get: ^4.6.5

  #Google Fonts
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

